### ISSUE TITLE
Revision of Requirements & Mockups

### ISSUE THREAD

**Issue by gozdeberk** [bounswe/bounswe2016group2#57]
- Revise and update requirements
- Prepare mockups to demonstrate the key requirements

**Comment by eu42** [comment]
Following requirements are updated:

1.1.1.2. Guest shall provide a username, a valid email address, and a password to sign up as a user.
1.1.1.3 Guest shall provide a Server name, a valid email address, the tax ID number of the Server,  a phone number, and a password to sign up as a Server.
&nbsp;&nbsp;&nbsp;&nbsp;1.1.1.3.1 The created account shall be confirmed through provided tax ID number.

1.2.1.3.1.2 User shall be able to select a time period for her calorie consumption. 

1.2.1.2.3. Users shall be able to follow ~~other users and~~ servers.

**Comment by eu42** [comment]
**Server Page - User view - Web**
![serverpage-user_web](https://cloud.githubusercontent.com/assets/15113365/19244665/11114654-8f26-11e6-9cea-c153d57c0944.png)

**Comment by enesozi** [comment]
![new serverpage-user_web](https://cloud.githubusercontent.com/assets/8464165/19245795/bb868c98-8f2b-11e6-9fad-6f56b2b4e81d.png)

**Comment by eu42** [comment]
**Server Page Comment - User View - Web**

![servercomment-user_web](https://cloud.githubusercontent.com/assets/15113365/19330500/7421add4-90e7-11e6-98b0-6e704c203b04.png)

**Comment by enesozi** [comment]
![new serverpage-user_web 1](https://cloud.githubusercontent.com/assets/8464165/19246552/95c94992-8f2f-11e6-9116-421e6d166ceb.png)

**Comment by enesozi** [comment]
![advance search 1](https://cloud.githubusercontent.com/assets/8464165/19246743/822c0054-8f30-11e6-9a42-39268e57e28e.png)

**Comment by enesozi** [comment]
![advance search 2](https://cloud.githubusercontent.com/assets/8464165/19249542/d13592a6-8f3e-11e6-87e6-c16b2ebfdf4a.png)

**Comment by gozdeberk** [comment]
![login or sign up](https://cloud.githubusercontent.com/assets/17164370/19330534/b029cb86-90e7-11e6-888e-832865e52650.png)

**Comment by gozdeberk** [comment]
![login](https://cloud.githubusercontent.com/assets/17164370/19330544/c0ee0680-90e7-11e6-8c56-2c669b553c58.png)

**Comment by gozdeberk** [comment]
![sign up as user](https://cloud.githubusercontent.com/assets/17164370/19330552/c9985c68-90e7-11e6-8c58-78951a217076.png)

**Comment by gozdeberk** [comment]
![sign up as server](https://cloud.githubusercontent.com/assets/17164370/19330559/d1b46f22-90e7-11e6-8fd6-c569aee71658.png)

**Comment by gozdeberk** [comment]
![food page 1](https://cloud.githubusercontent.com/assets/17164370/19330564/db19880e-90e7-11e6-8040-2521ebc00e0d.png)

**Comment by gozdeberk** [comment]
![server page 1](https://cloud.githubusercontent.com/assets/17164370/19330577/e67a403a-90e7-11e6-8bad-1562df8b2d33.png)

**Comment by eu42** [comment]
![server sign up - web](https://cloud.githubusercontent.com/assets/15113365/19331224/1bc8b1c8-90ec-11e6-8b17-16d52a4d42d4.png)
![sign up - web](https://cloud.githubusercontent.com/assets/15113365/19331225/1bca8d40-90ec-11e6-8933-19411bab88fa.png)

**Comment by yigitozgumus** [comment]
![Search Functionality](https://cloud.githubusercontent.com/assets/5840669/19342483/b603457a-913a-11e6-8fff-9ae526ccf32c.png)

**Comment by yigitozgumus** [comment]
![comment page](https://cloud.githubusercontent.com/assets/5840669/19343247/080ed548-913e-11e6-87c3-ec529debb7e2.png)

**Comment by yigitozgumus** [comment]
![writing comment](https://cloud.githubusercontent.com/assets/5840669/19343546/4fb80134-913f-11e6-9d20-fe071ad7aac7.png)

**Comment by mrtsnnacln** [comment]
![guest visits homepage](https://cloud.githubusercontent.com/assets/12100567/19410161/97bf1f9e-92ed-11e6-821d-d3ce40caa3c5.png)

**Comment by ghost** [comment]
![user goes to profile page](https://cloud.githubusercontent.com/assets/7761592/20112060/7a4e8d50-a5f3-11e6-8c50-34bd881fed37.png)
